```yaml
name: Atualizar Doadores

on:
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-doadores:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas PyGithub

      - name: Executar script doadores
        env:
          DOADORES: ${{ secrets.DOADORES }}
        run: |
          cd ${GITHUB_WORKSPACE}  # Garante que está na raiz do repositório
          python scripts/doadores.py

      - name: Commit e push alterações
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add dados/doadores.json
          git commit -m 'Atualização automática de doadores.json' || echo "Sem alterações para commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
